/**
 * Operator email signatures.
 *
 * Outreach emails generated by dm-writer / dm-rewrite get a small contact
 * card appended to the body. Three lines: full name, email, website. Plain
 * text only — the body lands in the operator's Gmail compose draft and gets
 * pasted manually, so HTML signatures would just show up as raw tags.
 *
 * Scope (decided 2026-05-21): emails ONLY. Cold DMs and DM follow-ups never
 * get a signature appended because Instagram doesn't have one, and stuffing
 * three contact lines into a 1000-char DM eats the budget.
 *
 * Source of truth lives in this file — hardcoded for the two-person team.
 * Adding a third operator means adding a row to OPERATOR_SIGNATURES and
 * redeploying. If the team grows past three or four people, this should
 * move to a Settings page backed by the user record in lib/users.js.
 */

// Canonical key for signature lookup. Lowercased + diacritics stripped so
// "Tomás" and "Tomas" both resolve to the same record. Mirrors the
// canonicalKey() pattern already used in lib/teamStats.js so operators are
// keyed identically across the codebase.
function canonicalize(s) {
  if (!s) return '';
  return String(s)
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .trim();
}

const OPERATOR_SIGNATURES = {
  tomas: {
    fullName: 'Tomás Massano',
    email: 'tom@secondlayerhq.com',
    website: 'secondlayerhq.com',
  },
  raul: {
    fullName: 'Raúl',
    email: 'raul@secondlayerhq.com',
    website: 'secondlayerhq.com',
  },
};
// The new email local-part is "tom" (not "tomas"), so an email-based lookup
// (getSignature('tom@secondlayerhq.com')) canonicalizes to "tom". Alias it to
// the same record so the signature still resolves whether the caller passes
// the name ("Tomás" → "tomas") or the new address ("tom").
OPERATOR_SIGNATURES.tom = OPERATOR_SIGNATURES.tomas;

/**
 * Look up the signature record for an operator. Accepts either a first name
 * ("Tomás", "raul") or an email ("tomas@informallabs.com") so callers can
 * pass whatever they have on hand without normalising upstream.
 *
 * Returns null when no match — the caller should leave the email body
 * untouched rather than appending a half-filled card.
 */
export function getSignature(senderIdentifier) {
  if (!senderIdentifier) return null;
  const raw = String(senderIdentifier).toLowerCase().trim();
  // Email path — split off the local part and canonicalize.
  if (raw.includes('@')) {
    const local = canonicalize(raw.split('@')[0]);
    return OPERATOR_SIGNATURES[local] || null;
  }
  // Name path.
  return OPERATOR_SIGNATURES[canonicalize(raw)] || null;
}

/**
 * Build the plain-text contact card. Three lines, no separator above —
 * callers are expected to insert two newlines between the email's existing
 * sign-off and the signature block.
 */
export function formatSignature(senderIdentifier) {
  const sig = getSignature(senderIdentifier);
  if (!sig) return '';
  return `${sig.fullName}\n${sig.email}\n${sig.website}`;
}

/**
 * Append the contact card to an email body. Idempotent — if the signature
 * already appears at the end (operator regenerated, signature got appended
 * twice would be ugly), we skip. Trims trailing whitespace from the body
 * first so the blank line between sign-off and signature is exactly one.
 *
 * Returns the body unchanged when no signature record exists for the
 * sender (third operator we haven't hardcoded yet, missing input, etc.).
 */
export function appendSignature(emailBody, senderIdentifier) {
  if (!emailBody) return emailBody;
  const sig = formatSignature(senderIdentifier);
  if (!sig) return emailBody;
  const trimmed = String(emailBody).trimEnd();
  // Idempotency check — bail if the contact card is already at the tail.
  if (trimmed.endsWith(sig)) return trimmed;
  return `${trimmed}\n\n${sig}`;
}
